# Generated by Django 3.0.2 on 2020-07-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANKING_MODEL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_phone',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
