# Generated by Django 3.0.2 on 2020-07-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BANKING_MODEL', '0002_auto_20200718_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user_account_type',
        ),
    ]
