# Generated by Django 3.0.2 on 2020-07-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANKING_MODEL', '0003_remove_user_details_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_account_type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
