# Generated by Django 3.0.2 on 2020-07-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANKING_MODEL', '0004_user_details_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_phone',
            field=models.IntegerField(unique=True),
        ),
    ]
