# Generated by Django 3.0.2 on 2020-07-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANKING_MODEL', '0006_auto_20200718_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANKING_MODEL.Account_type'),
        ),
    ]
