# Generated by Django 3.0.2 on 2020-07-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANKING_MODEL', '0008_remove_user_details_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
