# Generated by Django 3.0.2 on 2020-07-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANKING_MODEL', '0009_user_details_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_status',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
